title: TAFLAB Documentation
description: A site to document code and designs for the Berkeley TAFLab
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  TAFLab Github: https://github.com/Berkeley-TAFLab 

